// flow-typed signature: 7f7e4c6c4025943f128a942937717da3
// flow-typed version: <<STUB>>/consolidate_v^0.14.5/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'consolidate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'consolidate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'consolidate/lib/consolidate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'consolidate/index' {
  declare module.exports: $Exports<'consolidate'>;
}
declare module 'consolidate/index.js' {
  declare module.exports: $Exports<'consolidate'>;
}
declare module 'consolidate/lib/consolidate.js' {
  declare module.exports: $Exports<'consolidate/lib/consolidate'>;
}
