// flow-typed signature: c0b65edd7c52b35b9c2e066921f0599a
// flow-typed version: <<STUB>>/hbs_v^4.0.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hbs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'hbs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hbs/examples/extend/app' {
  declare module.exports: any;
}

declare module 'hbs/examples/partial/app' {
  declare module.exports: any;
}

declare module 'hbs/lib/async' {
  declare module.exports: any;
}

declare module 'hbs/lib/hbs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hbs/examples/extend/app.js' {
  declare module.exports: $Exports<'hbs/examples/extend/app'>;
}
declare module 'hbs/examples/partial/app.js' {
  declare module.exports: $Exports<'hbs/examples/partial/app'>;
}
declare module 'hbs/lib/async.js' {
  declare module.exports: $Exports<'hbs/lib/async'>;
}
declare module 'hbs/lib/hbs.js' {
  declare module.exports: $Exports<'hbs/lib/hbs'>;
}
