// flow-typed signature: 7aeaeffbc303f69fde774dd19a63c23e
// flow-typed version: <<STUB>>/help_v^3.0.2/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'help'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'help' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'help/test/fixtures/default/index' {
  declare module.exports: any;
}

declare module 'help/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'help/index' {
  declare module.exports: $Exports<'help'>;
}
declare module 'help/index.js' {
  declare module.exports: $Exports<'help'>;
}
declare module 'help/test/fixtures/default/index.js' {
  declare module.exports: $Exports<'help/test/fixtures/default/index'>;
}
declare module 'help/test/test.js' {
  declare module.exports: $Exports<'help/test/test'>;
}
