// flow-typed signature: 3cc5c4be47674c64efa1c34703e75941
// flow-typed version: <<STUB>>/mu2_v^0.5.21/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mu2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mu2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mu2/lib/mu-cli' {
  declare module.exports: any;
}

declare module 'mu2/lib/mu' {
  declare module.exports: any;
}

declare module 'mu2/lib/mu/errors' {
  declare module.exports: any;
}

declare module 'mu2/lib/mu/parser' {
  declare module.exports: any;
}

declare module 'mu2/lib/mu/renderer' {
  declare module.exports: any;
}

declare module 'mu2/lib/mu/stream' {
  declare module.exports: any;
}

declare module 'mu2/test/bench' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/boolean' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/carriage_return' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/comments' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/complex' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/date' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/deep_partial' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/delimiters' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/dot_notation' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/error_not_found' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/escaped' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/hash_instead_of_array' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/inverted' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/partial' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/recursion_with_same_names' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/reuse_of_enumerables' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/simple' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/tenthousand' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/twice' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/two_in_a_row' {
  declare module.exports: any;
}

declare module 'mu2/test/examples/unescaped' {
  declare module.exports: any;
}

declare module 'mu2/test/run_examples_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mu2/index' {
  declare module.exports: $Exports<'mu2'>;
}
declare module 'mu2/index.js' {
  declare module.exports: $Exports<'mu2'>;
}
declare module 'mu2/lib/mu-cli.js' {
  declare module.exports: $Exports<'mu2/lib/mu-cli'>;
}
declare module 'mu2/lib/mu.js' {
  declare module.exports: $Exports<'mu2/lib/mu'>;
}
declare module 'mu2/lib/mu/errors.js' {
  declare module.exports: $Exports<'mu2/lib/mu/errors'>;
}
declare module 'mu2/lib/mu/parser.js' {
  declare module.exports: $Exports<'mu2/lib/mu/parser'>;
}
declare module 'mu2/lib/mu/renderer.js' {
  declare module.exports: $Exports<'mu2/lib/mu/renderer'>;
}
declare module 'mu2/lib/mu/stream.js' {
  declare module.exports: $Exports<'mu2/lib/mu/stream'>;
}
declare module 'mu2/test/bench.js' {
  declare module.exports: $Exports<'mu2/test/bench'>;
}
declare module 'mu2/test/examples/boolean.js' {
  declare module.exports: $Exports<'mu2/test/examples/boolean'>;
}
declare module 'mu2/test/examples/carriage_return.js' {
  declare module.exports: $Exports<'mu2/test/examples/carriage_return'>;
}
declare module 'mu2/test/examples/comments.js' {
  declare module.exports: $Exports<'mu2/test/examples/comments'>;
}
declare module 'mu2/test/examples/complex.js' {
  declare module.exports: $Exports<'mu2/test/examples/complex'>;
}
declare module 'mu2/test/examples/date.js' {
  declare module.exports: $Exports<'mu2/test/examples/date'>;
}
declare module 'mu2/test/examples/deep_partial.js' {
  declare module.exports: $Exports<'mu2/test/examples/deep_partial'>;
}
declare module 'mu2/test/examples/delimiters.js' {
  declare module.exports: $Exports<'mu2/test/examples/delimiters'>;
}
declare module 'mu2/test/examples/dot_notation.js' {
  declare module.exports: $Exports<'mu2/test/examples/dot_notation'>;
}
declare module 'mu2/test/examples/error_not_found.js' {
  declare module.exports: $Exports<'mu2/test/examples/error_not_found'>;
}
declare module 'mu2/test/examples/escaped.js' {
  declare module.exports: $Exports<'mu2/test/examples/escaped'>;
}
declare module 'mu2/test/examples/hash_instead_of_array.js' {
  declare module.exports: $Exports<'mu2/test/examples/hash_instead_of_array'>;
}
declare module 'mu2/test/examples/inverted.js' {
  declare module.exports: $Exports<'mu2/test/examples/inverted'>;
}
declare module 'mu2/test/examples/partial.js' {
  declare module.exports: $Exports<'mu2/test/examples/partial'>;
}
declare module 'mu2/test/examples/recursion_with_same_names.js' {
  declare module.exports: $Exports<'mu2/test/examples/recursion_with_same_names'>;
}
declare module 'mu2/test/examples/reuse_of_enumerables.js' {
  declare module.exports: $Exports<'mu2/test/examples/reuse_of_enumerables'>;
}
declare module 'mu2/test/examples/simple.js' {
  declare module.exports: $Exports<'mu2/test/examples/simple'>;
}
declare module 'mu2/test/examples/tenthousand.js' {
  declare module.exports: $Exports<'mu2/test/examples/tenthousand'>;
}
declare module 'mu2/test/examples/twice.js' {
  declare module.exports: $Exports<'mu2/test/examples/twice'>;
}
declare module 'mu2/test/examples/two_in_a_row.js' {
  declare module.exports: $Exports<'mu2/test/examples/two_in_a_row'>;
}
declare module 'mu2/test/examples/unescaped.js' {
  declare module.exports: $Exports<'mu2/test/examples/unescaped'>;
}
declare module 'mu2/test/run_examples_test.js' {
  declare module.exports: $Exports<'mu2/test/run_examples_test'>;
}
