// flow-typed signature: 1f4c7eae2289aa4efdd026482c0c2372
// flow-typed version: <<STUB>>/rollup-plugin-svelte_v^1.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-svelte'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-svelte' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-svelte/dist/rollup-plugin-svelte.cjs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-svelte/dist/rollup-plugin-svelte.es' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-svelte/dist/rollup-plugin-svelte.cjs.js' {
  declare module.exports: $Exports<'rollup-plugin-svelte/dist/rollup-plugin-svelte.cjs'>;
}
declare module 'rollup-plugin-svelte/dist/rollup-plugin-svelte.es.js' {
  declare module.exports: $Exports<'rollup-plugin-svelte/dist/rollup-plugin-svelte.es'>;
}
