// flow-typed signature: fcf54876bfb22ab8f51c2509e62a8e3b
// flow-typed version: <<STUB>>/vulcanize_v^1.15.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vulcanize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vulcanize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vulcanize/lib/comment-map' {
  declare module.exports: any;
}

declare module 'vulcanize/lib/constants' {
  declare module.exports: any;
}

declare module 'vulcanize/lib/matchers' {
  declare module.exports: any;
}

declare module 'vulcanize/lib/pathresolver' {
  declare module.exports: any;
}

declare module 'vulcanize/lib/vulcan' {
  declare module.exports: any;
}

declare module 'vulcanize/third_party/UglifyJS2/output' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vulcanize/lib/comment-map.js' {
  declare module.exports: $Exports<'vulcanize/lib/comment-map'>;
}
declare module 'vulcanize/lib/constants.js' {
  declare module.exports: $Exports<'vulcanize/lib/constants'>;
}
declare module 'vulcanize/lib/matchers.js' {
  declare module.exports: $Exports<'vulcanize/lib/matchers'>;
}
declare module 'vulcanize/lib/pathresolver.js' {
  declare module.exports: $Exports<'vulcanize/lib/pathresolver'>;
}
declare module 'vulcanize/lib/vulcan.js' {
  declare module.exports: $Exports<'vulcanize/lib/vulcan'>;
}
declare module 'vulcanize/third_party/UglifyJS2/output.js' {
  declare module.exports: $Exports<'vulcanize/third_party/UglifyJS2/output'>;
}
