// flow-typed signature: 322875bdddceccd02dee74ce7ade9538
// flow-typed version: <<STUB>>/@polymer/polymer_v^1.2.5-npm-test.2/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@polymer/polymer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@polymer/polymer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@polymer/polymer/gulpfile' {
  declare module.exports: any;
}

declare module '@polymer/polymer/test/unit/polymer-dom' {
  declare module.exports: any;
}

declare module '@polymer/polymer/test/unit/ready' {
  declare module.exports: any;
}

// Filename aliases
declare module '@polymer/polymer/gulpfile.js' {
  declare module.exports: $Exports<'@polymer/polymer/gulpfile'>;
}
declare module '@polymer/polymer/test/unit/polymer-dom.js' {
  declare module.exports: $Exports<'@polymer/polymer/test/unit/polymer-dom'>;
}
declare module '@polymer/polymer/test/unit/ready.js' {
  declare module.exports: $Exports<'@polymer/polymer/test/unit/ready'>;
}
